package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/obcode/tallox.go/graph/model"
	"github.com/obcode/tallox.go/internal/policy"
	"github.com/obcode/tallox.go/internal/principal"
)

// Me is the resolver for the me field.
//
// Thin, like every resolver here: it reads the actor the auth middleware put in the context
// and reshapes it. There is no lookup, because there is nothing left to look up — the
// authenticators resolved the person and their grants in one query, which is also why a
// caller can trust this answer to describe the permissions the request will actually be
// judged by rather than a second opinion about them.
//
// Unauthenticated callers get null rather than an error: "nobody is logged in" is a state the
// GUI renders, not an exception it catches.
//
// The roles go through policy.RolesOf, so a grant the policy does not recognise is dropped
// here exactly as it is dropped everywhere else. Telling a caller they hold a role that
// grants nothing would be worse than not mentioning it.
func (r *queryResolver) Me(ctx context.Context) (*model.Person, error) {
	actor := principal.From(ctx)
	if !actor.Authenticated() {
		return nil, nil
	}

	return &model.Person{
		ID:    actor.ID.String(),
		Mail:  actor.Mail,
		Name:  actor.Name,
		Roles: policy.RolesOf(actor).Sorted(),
	}, nil
}
