package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/obcode/tallox.go/graph/generated"
	"github.com/obcode/tallox.go/internal/buildinfo"
)

// BuildInfo is the resolver for the buildInfo field.
func (r *queryResolver) BuildInfo(_ context.Context) (*buildinfo.Info, error) {
	return &r.Build, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
