package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"

	"github.com/obcode/tallox.go/graph/model"
	"github.com/obcode/tallox.go/internal/domain"
	"github.com/obcode/tallox.go/internal/policy"
	"github.com/obcode/tallox.go/internal/principal"
)

// CreateSemester is the resolver for the createSemester field.
func (r *mutationResolver) CreateSemester(ctx context.Context, code string) (*model.Semester, error) {
	created, err := r.Planning.Create(ctx, principal.From(ctx), code)
	if err != nil {
		return nil, semesterUserFacing(err)
	}
	return semesterModel(created), nil
}

// AdvanceSemesterPhase is the resolver for the advanceSemesterPhase field.
func (r *mutationResolver) AdvanceSemesterPhase(ctx context.Context, id string, to policy.Phase) (*model.Semester, error) {
	semesterUUID, err := semesterID(id)
	if err != nil {
		return nil, semesterUserFacing(err)
	}

	switched, err := r.Planning.AdvancePhase(ctx, principal.From(ctx), semesterUUID, to)
	if err != nil {
		return nil, semesterUserFacing(err)
	}
	return semesterModel(switched), nil
}

// PublishWishes is the resolver for the publishWishes field.
func (r *mutationResolver) PublishWishes(ctx context.Context, id string) (*model.Semester, error) {
	semesterUUID, err := semesterID(id)
	if err != nil {
		return nil, semesterUserFacing(err)
	}

	published, err := r.Planning.PublishWishes(ctx, principal.From(ctx), semesterUUID)
	if err != nil {
		// The publishing refusal names the door as well as the role — a caller who hits it
		// most often *has* DEANS_OFFICE and is using a token, and "only the dean's office may
		// do this" would send them to ask for a grant they already hold.
		if errors.Is(err, domain.ErrForbidden) {
			return nil, refusal("FORBIDDEN", policy.PublishWishesReason)
		}
		return nil, semesterUserFacing(err)
	}
	return semesterModel(published), nil
}

// Semesters is the resolver for the semesters field.
func (r *queryResolver) Semesters(ctx context.Context) ([]*model.Semester, error) {
	list, err := r.Planning.List(ctx, principal.From(ctx))
	if err != nil {
		return nil, semesterUserFacing(err)
	}

	out := make([]*model.Semester, 0, len(list))
	for _, s := range list {
		out = append(out, semesterModel(s))
	}
	return out, nil
}

// Semester is the resolver for the semester field.
func (r *queryResolver) Semester(ctx context.Context, id string) (*model.Semester, error) {
	semesterUUID, err := semesterID(id)
	if err != nil {
		// Nullable field, and an unknown id is an ordinary answer rather than a failure — the
		// same reading `me` gives an anonymous caller. A refusal is reserved for "you may not
		// ask", which List and this share and which comes out of the policy below.
		return nil, nil
	}

	found, err := r.Planning.ByID(ctx, principal.From(ctx), semesterUUID)
	if err != nil {
		if errors.Is(err, domain.ErrNoSuchSemester) {
			return nil, nil
		}
		return nil, semesterUserFacing(err)
	}
	return semesterModel(found), nil
}
