package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/obcode/tallox.go/graph/generated"
	"github.com/obcode/tallox.go/graph/model"
	"github.com/obcode/tallox.go/internal/principal"
)

// CreatePersonalAccessToken is the resolver for the createPersonalAccessToken field.
func (r *mutationResolver) CreatePersonalAccessToken(ctx context.Context, description string, expiresInDays *int, scopes []*model.ScopeGrantInput) (*model.CreatedPersonalAccessToken, error) {
	created, err := r.Tokens.Create(ctx, principal.From(ctx), description, expiresInDays,
		requestedScopes(scopes))
	if err != nil {
		return nil, userFacing(err)
	}

	return &model.CreatedPersonalAccessToken{
		Token:  tokenModel(created.Record),
		Secret: created.Plaintext,
	}, nil
}

// RevokePersonalAccessToken is the resolver for the revokePersonalAccessToken field.
func (r *mutationResolver) RevokePersonalAccessToken(ctx context.Context, id string) (*model.PersonalAccessToken, error) {
	record, err := r.Tokens.Revoke(ctx, principal.From(ctx), id)
	if err != nil {
		return nil, userFacing(err)
	}
	return tokenModel(record), nil
}

// MyTokens is the resolver for the myTokens field.
func (r *queryResolver) MyTokens(ctx context.Context) ([]*model.PersonalAccessToken, error) {
	records, err := r.Tokens.List(ctx, principal.From(ctx))
	if err != nil {
		return nil, userFacing(err)
	}

	out := make([]*model.PersonalAccessToken, 0, len(records))
	for _, record := range records {
		out = append(out, tokenModel(record))
	}
	return out, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
