// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/obcode/tallox.go/internal/policy"
)

// A newly created token: the record, and the one and only sight of the secret.
type CreatedPersonalAccessToken struct {
	// The token as it will appear in your list from now on.
	Token *PersonalAccessToken `json:"token"`
	// The complete token, `tallox_<id>_<secret>` — put this in your script's environment.
	//
	// Shown once, here, and never again: the server keeps only a checksum. If you lose it, revoke
	// this token and create another one. That is a two-second inconvenience, and it is the reason
	// a leak of the database is not a leak of anybody's credentials.
	Secret string `json:"secret"`
}

// Everything that changes something.
//
// All of it is `@interactiveOnly` for now: writing happens in a signed-in browser session, not
// through a Personal Access Token.
type Mutation struct {
}

// A person in the planning.
//
// Carries identity and roles, nothing else. Teaching load and notes about people are not
// reachable here — see the `@interactiveOnly` note in the API documentation.
type Person struct {
	ID string `json:"id"`
	// The address the university's login asserts. Case-insensitive, and the key we match on.
	Mail string `json:"mail"`
	Name string `json:"name"`
	// The roles this person holds, in a stable order.
	Roles []policy.Role `json:"roles"`
}

// A Personal Access Token, as its owner sees it.
//
// The secret is not here and never will be: the server keeps only a checksum of it, so no query
// can hand it out a second time.
type PersonalAccessToken struct {
	// The public half of the token — the part between the two underscores in `tallox_…_…`.
	//
	// Safe to write down, safe to read out over the phone. It identifies the token in this list
	// and in the audit log, and it is what you pass to `revokePersonalAccessToken`.
	ID string `json:"id"`
	// What you called it. Shown in the list, so that revoking the right one is not guesswork.
	Description string `json:"description"`
	// The `area:verb` grants this token carries.
	//
	// Currently informational: every token can do what its owner can. Fine-grained scopes are
	// planned, and tokens created now will keep working when they arrive.
	Scopes    []string  `json:"scopes"`
	CreatedAt time.Time `json:"createdAt"`
	// When this token stops working. There is no token without an expiry: 90 days by default, 365
	// at most.
	ExpiresAt time.Time `json:"expiresAt"`
	// Roughly when the token was last used, or `null` if it never was.
	//
	// Deliberately coarse — it is only updated when the previous value is more than five minutes
	// old. It answers "is this still in use, can I revoke it", which is what it is for.
	LastUsedAt *time.Time `json:"lastUsedAt,omitempty"`
	// When it was withdrawn, or `null` while it still works.
	RevokedAt *time.Time `json:"revokedAt,omitempty"`
}

// Everything that can be read.
//
// Start with `me` to check that your token works and to see which roles you hold — the roles
// decide what the rest of these fields answer.
type Query struct {
}
