// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package store

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Person struct {
	ID        uuid.UUID
	Mail      string
	Name      string
	Active    bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type PersonRole struct {
	PersonID  uuid.UUID
	Role      string
	GrantedAt time.Time
	GrantedBy uuid.NullUUID
}

type PersonalAccessToken struct {
	TokenID     string
	OwnerID     uuid.UUID
	SecretHash  []byte
	Description string
	Scopes      []string
	CreatedAt   time.Time
	ExpiresAt   time.Time
	LastUsedAt  pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
}
