// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: person.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createPerson = `-- name: CreatePerson :one

INSERT INTO person (id, mail, name)
VALUES ($1, $2, $3)
RETURNING id, mail, name, active, created_at, updated_at
`

type CreatePersonParams struct {
	ID   uuid.UUID
	Mail string
	Name string
}

// People and their role grants.
//
// Every read that resolves an identity returns the roles with it, in one round trip. Two
// queries would mean a window in which a person exists and their grants do not, and the
// authenticator would have to decide what to do with a caller whose permissions it could not
// read — a decision with only bad answers.
// The id is supplied by the caller rather than defaulted, so that a fixture, a seed and an
// import can all say who they are creating before the insert happens.
func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, createPerson, arg.ID, arg.Mail, arg.Name)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Mail,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const grantRole = `-- name: GrantRole :exec
INSERT INTO person_role (person_id, role, granted_by)
VALUES ($1, $2, $3)
ON CONFLICT (person_id, role) DO NOTHING
`

type GrantRoleParams struct {
	PersonID  uuid.UUID
	Role      string
	GrantedBy uuid.NullUUID
}

// Idempotent: granting a role somebody already holds is not an error, and the alternative
// would push every caller into a read-then-write race.
func (q *Queries) GrantRole(ctx context.Context, arg GrantRoleParams) error {
	_, err := q.db.Exec(ctx, grantRole, arg.PersonID, arg.Role, arg.GrantedBy)
	return err
}

const personByID = `-- name: PersonByID :one
SELECT
    p.id,
    p.mail,
    p.name,
    p.active,
    COALESCE(
        array_agg(pr.role ORDER BY pr.role) FILTER (WHERE pr.role IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS roles
FROM person p
LEFT JOIN person_role pr ON pr.person_id = p.id
WHERE p.id = $1
GROUP BY p.id
`

type PersonByIDRow struct {
	ID     uuid.UUID
	Mail   string
	Name   string
	Active bool
	Roles  []string
}

func (q *Queries) PersonByID(ctx context.Context, id uuid.UUID) (PersonByIDRow, error) {
	row := q.db.QueryRow(ctx, personByID, id)
	var i PersonByIDRow
	err := row.Scan(
		&i.ID,
		&i.Mail,
		&i.Name,
		&i.Active,
		&i.Roles,
	)
	return i, err
}

const personByMail = `-- name: PersonByMail :one
SELECT
    p.id,
    p.mail,
    p.name,
    p.active,
    COALESCE(
        array_agg(pr.role ORDER BY pr.role) FILTER (WHERE pr.role IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS roles
FROM person p
LEFT JOIN person_role pr ON pr.person_id = p.id
WHERE p.mail = $1
GROUP BY p.id
`

type PersonByMailRow struct {
	ID     uuid.UUID
	Mail   string
	Name   string
	Active bool
	Roles  []string
}

// The authentication query of the browser door. mail is citext, so the comparison is
// case-insensitive without a lower() that would defeat the unique index.
func (q *Queries) PersonByMail(ctx context.Context, mail string) (PersonByMailRow, error) {
	row := q.db.QueryRow(ctx, personByMail, mail)
	var i PersonByMailRow
	err := row.Scan(
		&i.ID,
		&i.Mail,
		&i.Name,
		&i.Active,
		&i.Roles,
	)
	return i, err
}

const revokeRole = `-- name: RevokeRole :exec
DELETE FROM person_role
WHERE person_id = $1 AND role = $2
`

type RevokeRoleParams struct {
	PersonID uuid.UUID
	Role     string
}

func (q *Queries) RevokeRole(ctx context.Context, arg RevokeRoleParams) error {
	_, err := q.db.Exec(ctx, revokeRole, arg.PersonID, arg.Role)
	return err
}

const setPersonActive = `-- name: SetPersonActive :exec
UPDATE person
SET active = $2,
    updated_at = now()
WHERE id = $1
`

type SetPersonActiveParams struct {
	ID     uuid.UUID
	Active bool
}

// Deactivation is how a leaver loses access to everything at once, tokens included.
func (q *Queries) SetPersonActive(ctx context.Context, arg SetPersonActiveParams) error {
	_, err := q.db.Exec(ctx, setPersonActive, arg.ID, arg.Active)
	return err
}
