// Package store is the storage layer and the only package in this module that is allowed to
// talk to PostgreSQL. The architecture test in internal/arch enforces that.
//
// The reason is the wish-visibility rule. If resolvers, the domain layer or a future CSV
// export handler could reach pgx directly, every one of them would have to remember to apply
// the filter, and one forgotten call site is not a bug in this project — it is the political
// failure the whole system is meant to prevent. Funnelling every read through this package
// means the filter has exactly one home.
//
// Most of this package is generated by sqlc from db/queries/*.sql. The hand-written part is
// what sqlc does not do: opening the pool and applying migrations.
package store

import (
	"context"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
)

// Pool is the connection pool, named here so that the packages that merely hold one — the
// wiring in bootstrap — can say its type without importing pgxpool.
//
// An alias rather than a defined type: it has to remain assignable to what pgxpool returns,
// and the point is naming, not wrapping. Without it, bootstrap can pass a pool from one
// function to another only as long as it never writes a signature that mentions it, which is
// the sort of constraint that quietly breaks the moment somebody extracts a helper — and the
// arch test that stops them is right to.
type Pool = *pgxpool.Pool

// Open creates a connection pool and verifies it can actually reach the database.
//
// The ping is not ceremony: without it a wrong DSN surfaces later, on the first query, as a
// failure of whatever request happened to arrive first. Failing here means the server refuses
// to start, which the container healthcheck and the deploy script both understand.
func Open(ctx context.Context, dsn string) (*pgxpool.Pool, error) {
	cfg, err := pgxpool.ParseConfig(dsn)
	if err != nil {
		return nil, fmt.Errorf("cannot parse database url: %w", err)
	}

	// Every session lands in Europe/Berlin, matching time.Local as pinned in main.go.
	// Milestone deadlines and phase boundaries are local-time; a pool whose sessions default
	// to UTC would make date_trunc and ::date in a query disagree with the same computation
	// in Go, and only for the hours where it matters.
	if cfg.ConnConfig.RuntimeParams == nil {
		cfg.ConnConfig.RuntimeParams = map[string]string{}
	}
	if _, set := cfg.ConnConfig.RuntimeParams["timezone"]; !set {
		cfg.ConnConfig.RuntimeParams["timezone"] = "Europe/Berlin"
	}

	pool, err := pgxpool.NewWithConfig(ctx, cfg)
	if err != nil {
		return nil, fmt.Errorf("cannot create connection pool: %w", err)
	}

	pingCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()
	if err := pool.Ping(pingCtx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("cannot reach database: %w", err)
	}

	return pool, nil
}
