// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// How many people other than this one could still administer the installation.
	//
	// "Could still": active person, unexpired grant. A deactivated administrator and one whose
	// temporary grant ran out are both people who cannot let anybody back in, and counting them
	// would make the last-administrator guard pass at exactly the moment it is needed.
	//
	// Called under the advisory lock, never on its own.
	CountOtherActiveAdmins(ctx context.Context, personID uuid.UUID) (int64, error)
	// People and their role grants.
	//
	// Every read that resolves an identity returns the roles with it, in one round trip. Two
	// queries would mean a window in which a person exists and their grants do not, and the
	// authenticator would have to decide what to do with a caller whose permissions it could not
	// read — a decision with only bad answers.
	//
	// The expiry filter sits in the JOIN condition rather than in a WHERE clause, in every query
	// below. That is not a style preference: in a LEFT JOIN, a WHERE on the right-hand table
	// turns the join into an inner one, so a person whose only grant has expired would disappear
	// from the list entirely instead of appearing with no roles. The version that leaks is the
	// one that hides people from the administration screen.
	// The id is supplied by the caller rather than defaulted, so that a fixture, a seed and an
	// import can all say who they are creating before the insert happens.
	CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error)
	// Personal Access Tokens: the second door.
	// The secret is generated and hashed by the caller (internal/auth), never here: a secret that
	// travelled through a query is a secret in a log somewhere.
	CreateToken(ctx context.Context, arg CreateTokenParams) (CreateTokenRow, error)
	// Get this mail address a person row, creating one if there is none.
	//
	// The reconciliation of the protected administrators runs through here on every start, so it
	// has to be a no-op on the ordinary case. ON CONFLICT DO UPDATE rather than DO NOTHING,
	// because DO NOTHING returns no row and the caller would need a second query to find the id
	// of the person it just did not create.
	//
	// name is only written when the row is created: a person renamed through the interface, or by
	// a future ZPA import, must not be renamed back on the next restart by a value somebody typed
	// into a YAML file once. The DO UPDATE therefore writes a column back to itself — a true
	// no-op that still produces a row to return, which DO NOTHING does not.
	EnsurePerson(ctx context.Context, arg EnsurePersonParams) (Person, error)
	// Idempotent in the sense that matters: granting a role somebody already holds updates its
	// expiry rather than failing, so "give me DEANS_OFFICE for another hour" is one call and not
	// a read-then-write race.
	//
	// granted_at is refreshed with it. The row records the grant that is in force, and a
	// timestamp that pointed at a superseded one would be the wrong answer to the audit question.
	GrantRole(ctx context.Context, arg GrantRoleParams) error
	// The administration screen: everybody, or everybody active, optionally narrowed by a
	// substring of the mail address or the name.
	//
	// Ordered by name and then mail so that the list is stable between calls — an administration
	// table whose rows move between reloads is one where somebody eventually clicks the wrong
	// row. People with no name yet sort first, which is also where the work is.
	ListPeople(ctx context.Context, arg ListPeopleParams) ([]ListPeopleRow, error)
	// The token list in the GUI. The secret hash is not in the projection: nothing outside
	// authentication has a use for it, and a column that is never selected cannot be logged.
	ListTokensOfPerson(ctx context.Context, ownerID uuid.UUID) ([]ListTokensOfPersonRow, error)
	// Serialise every change that could remove the last administrator.
	//
	// The rule to protect is "at least one active person holds an unexpired ADMIN grant", and it
	// is a statement about a *set* of rows. Two administrators can each check it, each see the
	// other, and each commit a change that was only safe while the other did not happen — the
	// textbook write skew, and here its outcome is an installation nobody can get into.
	//
	// A single clever statement does not fix it, because the two dangerous operations touch
	// different tables: revoking ADMIN writes person_role, deactivating an administrator writes
	// person. What they have in common is these rows, so both take this lock first and the second
	// one waits and then re-reads.
	//
	// Row locks rather than an advisory lock on a constant: this is scoped to the current schema,
	// which is what lets the integration tests run in parallel, and it needs no magic number that
	// somebody else could pick again for something unrelated.
	LockAdminGrants(ctx context.Context) error
	// Coarse on purpose. "Last used" is answering "is this token still in use, can I revoke it",
	// and five-minute resolution answers that as well as microsecond resolution would.
	//
	// The guard is the point: without it, every API call takes a row lock and writes WAL, which
	// serialises the requests of a single script against itself and makes the busiest tokens the
	// slowest ones.
	MarkTokenUsed(ctx context.Context, tokenID string) error
	PersonByID(ctx context.Context, id uuid.UUID) (PersonByIDRow, error)
	// The authentication query of the browser door. mail is citext, so the comparison is
	// case-insensitive without a lower() that would defeat the unique index.
	PersonByMail(ctx context.Context, mail string) (PersonByMailRow, error)
	RevokeRole(ctx context.Context, arg RevokeRoleParams) error
	// A timestamp, not a DELETE: the audit log has to keep resolving this token id afterwards.
	// Idempotent — revoking twice keeps the first moment, which is the one that matters.
	RevokeToken(ctx context.Context, tokenID string) error
	// Revokes a token, but only the caller's own.
	//
	// Ownership is in the WHERE clause rather than in a read-then-write in Go, which collapses
	// three things into one: the check cannot race with a concurrent revocation, "no such token"
	// and "not your token" become the same empty result — the difference is not information the
	// caller is entitled to — and there is no window in which a token id has been confirmed to
	// exist before the write is refused.
	//
	// COALESCE keeps the first revocation moment. Revoking twice is not an error, and the moment
	// the audit log needs is the first one.
	RevokeTokenOfOwner(ctx context.Context, arg RevokeTokenOfOwnerParams) (RevokeTokenOfOwnerRow, error)
	// One person's grants as they actually are, expired ones included.
	//
	// Deliberately not filtered: this is the detail view, and "DEANS_OFFICE, granted on Tuesday
	// by X, expired on Wednesday" is the answer to the only question this table gets asked —
	// who could see what, when. The permission lookups above are the ones that filter.
	RoleGrantsByPerson(ctx context.Context, personID uuid.UUID) ([]RoleGrantsByPersonRow, error)
	// Deactivation is how a leaver loses access to everything at once, tokens included.
	//
	// The guard against deactivating the last administrator is not here. It cannot be: it depends
	// on a count over other rows, and a single statement that read that count would still race
	// with a concurrent deactivation. internal/store takes an advisory lock and checks first —
	// see AdminGrantLockKey.
	SetPersonActive(ctx context.Context, arg SetPersonActiveParams) error
	// Renaming somebody. Separate from the role and activity paths because it is the one edit
	// here that is not a permission change, and mixing it in would make every rename look like
	// one in the audit log.
	SetPersonName(ctx context.Context, arg SetPersonNameParams) error
	// The authentication query of the token door, in one round trip: the token, its owner and the
	// owner's roles.
	//
	// Permissions come from the person on every request, which is what makes "a token can never
	// exceed its owner's role" true by construction — revoking a role demotes every token that
	// person holds without touching a token row.
	//
	// Deliberately returns expired, revoked and inactive rows instead of filtering them out.
	// Authentication has to tell "this token does not exist" from "this token expired" — the
	// caller owns the token and can be told why it stopped working — and a query that filters
	// would collapse both into the same silence. It also keeps the timing of the two cases
	// similar, which a WHERE clause on revoked_at would not.
	TokenByID(ctx context.Context, tokenID string) (TokenByIDRow, error)
}

var _ Querier = (*Queries)(nil)
