// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// People and their role grants.
	//
	// Every read that resolves an identity returns the roles with it, in one round trip. Two
	// queries would mean a window in which a person exists and their grants do not, and the
	// authenticator would have to decide what to do with a caller whose permissions it could not
	// read — a decision with only bad answers.
	// The id is supplied by the caller rather than defaulted, so that a fixture, a seed and an
	// import can all say who they are creating before the insert happens.
	CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error)
	// Personal Access Tokens: the second door.
	// The secret is generated and hashed by the caller (internal/auth), never here: a secret that
	// travelled through a query is a secret in a log somewhere.
	CreateToken(ctx context.Context, arg CreateTokenParams) (CreateTokenRow, error)
	// Idempotent: granting a role somebody already holds is not an error, and the alternative
	// would push every caller into a read-then-write race.
	GrantRole(ctx context.Context, arg GrantRoleParams) error
	// The token list in the GUI. The secret hash is not in the projection: nothing outside
	// authentication has a use for it, and a column that is never selected cannot be logged.
	ListTokensOfPerson(ctx context.Context, ownerID uuid.UUID) ([]ListTokensOfPersonRow, error)
	// Coarse on purpose. "Last used" is answering "is this token still in use, can I revoke it",
	// and five-minute resolution answers that as well as microsecond resolution would.
	//
	// The guard is the point: without it, every API call takes a row lock and writes WAL, which
	// serialises the requests of a single script against itself and makes the busiest tokens the
	// slowest ones.
	MarkTokenUsed(ctx context.Context, tokenID string) error
	PersonByID(ctx context.Context, id uuid.UUID) (PersonByIDRow, error)
	// The authentication query of the browser door. mail is citext, so the comparison is
	// case-insensitive without a lower() that would defeat the unique index.
	PersonByMail(ctx context.Context, mail string) (PersonByMailRow, error)
	RevokeRole(ctx context.Context, arg RevokeRoleParams) error
	// A timestamp, not a DELETE: the audit log has to keep resolving this token id afterwards.
	// Idempotent — revoking twice keeps the first moment, which is the one that matters.
	RevokeToken(ctx context.Context, tokenID string) error
	// Deactivation is how a leaver loses access to everything at once, tokens included.
	SetPersonActive(ctx context.Context, arg SetPersonActiveParams) error
	// The authentication query of the token door, in one round trip: the token, its owner and the
	// owner's roles.
	//
	// Permissions come from the person on every request, which is what makes "a token can never
	// exceed its owner's role" true by construction — revoking a role demotes every token that
	// person holds without touching a token row.
	//
	// Deliberately returns expired, revoked and inactive rows instead of filtering them out.
	// Authentication has to tell "this token does not exist" from "this token expired" — the
	// caller owns the token and can be told why it stopped working — and a query that filters
	// would collapse both into the same silence. It also keeps the timing of the two cases
	// similar, which a WHERE clause on revoked_at would not.
	TokenByID(ctx context.Context, tokenID string) (TokenByIDRow, error)
}

var _ Querier = (*Queries)(nil)
