// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: semester.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const advanceSemesterPhase = `-- name: AdvanceSemesterPhase :one
UPDATE semester
SET phase = $2,
    updated_at = now()
WHERE id = $1
  AND phase = $3
RETURNING id, code, phase, wishes_published_at, created_at, updated_at
`

type AdvanceSemesterPhaseParams struct {
	ID      uuid.UUID
	Phase   string
	Phase_2 string
}

// Compare-and-set: $3 is the phase the caller believes the semester is in, and no rows come
// back if it has moved on since they looked.
//
// That is what makes "one step at a time" hold under concurrency. Without the second
// predicate, two switches issued together would both read DEMAND_PLANNING, and the second
// would write ASSIGNMENT over the first one's WISHES — a skipped phase, arrived at by nobody's
// decision, and invisible afterwards because the row looks like somebody chose it.
func (q *Queries) AdvanceSemesterPhase(ctx context.Context, arg AdvanceSemesterPhaseParams) (Semester, error) {
	row := q.db.QueryRow(ctx, advanceSemesterPhase, arg.ID, arg.Phase, arg.Phase_2)
	var i Semester
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Phase,
		&i.WishesPublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSemester = `-- name: CreateSemester :one

INSERT INTO semester (code)
VALUES ($1)
RETURNING id, code, phase, wishes_published_at, created_at, updated_at
`

// Semesters and the phase each one is in.
//
// Two of these are compare-and-set rather than plain updates, and that is the theme of the
// file. A phase advance and a publication are both "change this only if it is still what I
// think it is": the alternative is to read the row, decide in Go, and write — which is correct
// in a unit test and a race in production, because two people from the dean's office clicking
// at the same moment is precisely the situation a phase switch happens in.
// The code carries the format constraint, so an invalid one is refused by the database and
// not only by the service. The phase defaults to DEMAND_PLANNING: a semester that exists but
// has not been planned yet is at the start of the process, which is the only sensible reading.
func (q *Queries) CreateSemester(ctx context.Context, code string) (Semester, error) {
	row := q.db.QueryRow(ctx, createSemester, code)
	var i Semester
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Phase,
		&i.WishesPublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const publishSemesterWishes = `-- name: PublishSemesterWishes :one
UPDATE semester
SET wishes_published_at = COALESCE(wishes_published_at, now()),
    updated_at = CASE WHEN wishes_published_at IS NULL THEN now() ELSE updated_at END
WHERE id = $1
RETURNING id, code, phase, wishes_published_at, created_at, updated_at
`

// Idempotent, and it keeps the *first* timestamp.
//
// Publishing twice is not an error — the second caller wanted the wishes published and they
// are — but the moment it happened is a fact about the process that a second call must not
// overwrite. COALESCE does both in one statement, so there is no window between checking and
// writing.
//
// updated_at stays untouched when nothing changed, so a repeated call does not make the row
// look edited.
func (q *Queries) PublishSemesterWishes(ctx context.Context, id uuid.UUID) (Semester, error) {
	row := q.db.QueryRow(ctx, publishSemesterWishes, id)
	var i Semester
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Phase,
		&i.WishesPublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const semesterByCode = `-- name: SemesterByCode :one
SELECT id, code, phase, wishes_published_at, created_at, updated_at
FROM semester
WHERE code = $1
`

func (q *Queries) SemesterByCode(ctx context.Context, code string) (Semester, error) {
	row := q.db.QueryRow(ctx, semesterByCode, code)
	var i Semester
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Phase,
		&i.WishesPublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const semesterByID = `-- name: SemesterByID :one
SELECT id, code, phase, wishes_published_at, created_at, updated_at
FROM semester
WHERE id = $1
`

func (q *Queries) SemesterByID(ctx context.Context, id uuid.UUID) (Semester, error) {
	row := q.db.QueryRow(ctx, semesterByID, id)
	var i Semester
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Phase,
		&i.WishesPublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const semesters = `-- name: Semesters :many
SELECT id, code, phase, wishes_published_at, created_at, updated_at
FROM semester
ORDER BY code DESC
`

// Newest first, which for this code is also chronological: the year leads and S sorts before
// W within a year, in the order the terms actually happen. Ordering by created_at instead
// would list them by when somebody got round to entering them.
func (q *Queries) Semesters(ctx context.Context) ([]Semester, error) {
	rows, err := q.db.Query(ctx, semesters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Semester{}
	for rows.Next() {
		var i Semester
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Phase,
			&i.WishesPublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
